import Head from "next/head"

import { useRef } from 'react';

import Start from "../components/sections/Start";
import About from "../components/sections/About";
import Navbar from "../components/sections/Navbar";
import Projects from "../components/sections/Projects";
import Contact from "../components/sections/Contact";

export default function Home() {
  const refs = useRef([]);

  const handleScrollToSection = (index) => {
    console.log(refs.current[index])
    refs.current[index]?.scrollIntoView({behavior: 'smooth'});
  }

  return (
    <>
      <Head>
        <title>Alex Mot Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="bg-white  dark:bg-gray-800 h-full">
          <Navbar handleScrollToSection={handleScrollToSection} refs={refs} />
          <Start handleScrollToSection={handleScrollToSection} />
          <About refs={refs} />
          <Projects refs={refs} />
          <Contact refs={refs} />
        </main>
    </>
  )
}
